spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.229.130:7001
        - 192.168.229.130:7002
        - 192.168.229.130:7003
        - 192.168.229.130:7004
        - 192.168.229.130:7005
        - 192.168.229.130:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.229.128
    port: 5672
    username: admin
    password: 1111
    virtual-host: /
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
mybatis-plus:
  mapper-locations: classpath:mapper/**.xml # 映射文件的路径
  type-aliases-package: com.usian.vo,com.usian.pojo # 在映射文件中使用某个类时不用写全路径,简化写别名
